services:
  sp_real_time.configuration:
    class: SP\RealTimeBundle\RealTimeConfiguration
    arguments: ['@snc_redis.default', "%sp_real_time.configuration%"]

  SP\RealTimeBundle\RealTimeConfiguration: "@sp_real_time.configuration"

  sp_real_time.event_dispatcher:
    class: SP\RealTimeBundle\Event\EventDispatcher
    arguments: ["@event_dispatcher"]

  SP\RealTimeBundle\Event\EventDispatcher: "@sp_real_time.event_dispatcher"

  sp_real_time.presence:
    class: SP\RealTimeBundle\Presence\PresenceService
    arguments: ["@sp_real_time.configuration", "@sp_real_time.event_dispatcher"]
    public: true

  SP\RealTimeBundle\Presence\PresenceService: "@sp_real_time.presence"

  sp_real_time.sender:
    class: SP\RealTimeBundle\Message\SenderService
    arguments: ["@sp_real_time.configuration", "@sp_real_time.event_dispatcher", "@sp_real_time.presence"]
    public: true

  SP\RealTimeBundle\Message\SenderService: "@sp_real_time.sender"

  SP\RealTimeBundle\Command\SendMessageCommand:
    arguments: ['@sp_real_time.sender']
    tags:
      - { name: 'console.command', command: 'real_time:send' }

  SP\RealTimeBundle\Command\SyncCommand:
    arguments: ['@sp_real_time.presence']
    tags:
      - { name: 'console.command', command: 'real_time:sync' }

  SP\RealTimeBundle\Controller\PresenceController:
    calls:
      - method: setContainer
        arguments:
          - '@service_container'
    public: true

